### ISSUE TITLE
Unable to obtain infoseek_val_qtype.jsonl

### ISSUE THREAD

**Issue by rtanaka-lab** [edchengg/infoseek_eval#1]
Thank you for sharing the great work! 

I was wondering how we get the **infoseek_val_qtype.jsonl** to evaluate our model. 
Please share the way of obtaining it and also want to share download_infoseek_jsonl.sh.

**Comment by edchengg** [comment]
Thanks for your interest!
Here is a link to the jsonl that you requested:

`https://storage.googleapis.com/gresearch/open-vision-language/infoseek/infoseek_val_qtype.jsonl`

**Comment by rtanaka-lab** [comment]
Thank you for the quick response! 
I'm trying to evaluate our model!
