### ISSUE TITLE
The "id2image.jsonl" was lost

### ISSUE THREAD

**Issue by qiankunlee** [edchengg/infoseek_eval#5]
Hello,
  I can't find it in the repo! would you mind upload it again!

Thanks!

**Comment by edchengg** [comment]
Hi, please find all data in https://huggingface.co/datasets/ychenNLP/oven
I've closed google drive due to space limit
for id2image.jsonl, you can prepare it based on your own folder path
thanks!

**Comment by xiaofeng94** [comment]
Hey @edchengg, what is the mapping rule for `id2image.jsonl`, is the image_path as `<image_id> + <extension>`?
